name: Ansible CI

on:
  push:
  pull_request:

jobs:
  lint-and-dryrun:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Ansible and linters
        run: |
          python -m pip install --upgrade pip
          pip install "ansible>=9" ansible-lint yamllint

      - name: Lint YAML
        run: yamllint .

      - name: Lint Ansible
        run: ansible-lint

      - name: Show Ansible version
        run: ansible --version

      - name: Dry-run hello playbook (check mode)
        run: ansible-playbook playbooks/hello.yml --check -vv

